### ISSUE TITLE
New Supporting Concatenated SMS Example.

### ISSUE THREAD

**Issue by ingfraga** [AdhamAwadhi/JamaaSMPP#28]
Can you paste an example of concatenated SMS? because I'm receiving 2 or 3 separated messages.

**Comment by AdhamAwadhi** [comment]
**For Sending** it's already supported.
**For Receiving** We can not do that because it's needed to **store** the previous parts.
You need to implement your code. That is what I'm doing on `client_MessageReceived`:

![Smpp Recieveing Sms (3)](https://user-images.githubusercontent.com/1698106/62237709-28303080-b3da-11e9-9b0c-4fb867687175.png)
